package com.myspace.foo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SquareCalculator implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer num;
	private java.lang.Integer square;

	public SquareCalculator() {
	}

	public java.lang.Integer getNum() {
		return this.num;
	}

	public void setNum(java.lang.Integer num) {
		this.num = num;
	}

	public java.lang.Integer getSquare() {
		return this.square;
	}

	public void setSquare(java.lang.Integer square) {
		this.square = square;
	}

	public SquareCalculator(java.lang.Integer num, java.lang.Integer square) {
		this.num = num;
		this.square = square;
	}

}